framework:
    secret: '%env(APP_SECRET)%'
    default_locale: en
    csrf_protection: true
    http_method_override: true
    php_errors:
        log: true
    cache:
    session: ~
    validation:
       email_validation_mode: html5
    templating:
        engines:
            - twig

