sonata_admin:
    title: 'MOGONI'
    dashboard:
        blocks:
            - { type: sonata.admin.block.admin_list, position: left }

sonata_block:
    blocks:
        sonata.admin.block.admin_list:
        sonata.admin.block.search_result:
            contexts: [admin]

sonata_core:
    form:
        mapping:
            enabled: false